[project]
name = "chatbot-auth"
version = "0.1.0"
description = "Simple Chat-bot powered by Chainlit"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "google-generativeai>=0.8.5",
    "python-dotenv>=1.1.0",
]
